import requests
import random
import time

BASE_URL = "http://127.0.0.1:8000/api"

def print_step(msg):
    print(f"\n[{time.strftime('%H:%M:%S')}] 🚀 {msg}")

def test_simulation():
    print_step("Starting Croonfit End-to-End Simulation Test")

    # 1. Admin Login
    print_step("Logging in as Admin...")
    r = requests.post(f"{BASE_URL}/admin/login", json={"username": "admin", "password": "admin123"})
    if r.status_code != 200:
        print("❌ Admin login failed!", r.text)
        return
    admin_token = r.json()["access_token"]
    admin_headers = {"Authorization": f"Bearer {admin_token}"}
    print("✅ Admin authenticated.")

    # 2. Wipe existing products (Truncate or Delete all)
    print_step("Wiping all existing products...")
    # Fetch all
    r = requests.get(f"{BASE_URL}/admin/products?per_page=100", headers=admin_headers)
    products = r.json().get("items", [])
    for p in products:
        requests.delete(f"{BASE_URL}/admin/products/{p['id']}", headers=admin_headers)
    print(f"✅ Wiped {len(products)} old products.")

    # Get categories to assign
    r = requests.get(f"{BASE_URL}/products/categories")
    categories = r.json()
    mens_id = next((c["id"] for c in categories if c["name"].lower() == "mens"), 1)
    womens_id = next((c["id"] for c in categories if c["name"].lower() == "womens"), 2)
    kids_id = next((c["id"] for c in categories if c["name"].lower() == "kids"), 3)

    # 3. Add 50 Products
    print_step("Adding 50 new products across Mens, Womens, Kids...")
    created_product_ids = []
    
    for i in range(1, 51):
        cat_id = random.choice([mens_id, womens_id, kids_id])
        payload = {
            "name": f"Simulated Product {i}",
            "slug": f"simulated-product-{i}-{int(time.time()*1000)}",
            "description": "High quality apparel generated by simulation.",
            "price": random.choice([1499.0, 1999.0, 2499.0, 2999.0]),
            "category_id": cat_id,
            "is_active": True,
            "tags": ["new", "simulated"],
            "variants": [
                {"size": "M", "color": "Black", "stock_qty": 50, "sku": f"SIM-{i}-M-BLK"},
                {"size": "L", "color": "Black", "stock_qty": 30, "sku": f"SIM-{i}-L-BLK"}
            ]
        }
        r = requests.post(f"{BASE_URL}/admin/products", json=payload, headers=admin_headers)
        if r.status_code == 201:
            created_product_ids.append(r.json()["id"])
        else:
            print(f"Failed to create product {i}: {r.text}")
    print(f"✅ Successfully added {len(created_product_ids)} products.")

    # 4. Delete 10 Products
    print_step("Deleting 10 products...")
    to_delete = created_product_ids[:10]
    for pid in to_delete:
        requests.delete(f"{BASE_URL}/admin/products/{pid}", headers=admin_headers)
        created_product_ids.remove(pid)
    print("✅ Successfully deleted 10 products.")

    # 5. Add 20 more Products
    print_step("Adding 20 more products...")
    for i in range(51, 71):
        cat_id = random.choice([mens_id, womens_id, kids_id])
        payload = {
            "name": f"Simulated Batch2 Product {i}",
            "slug": f"simulated-batch2-{i}-{int(time.time()*1000)}",
            "description": "Second batch of simulated products.",
            "price": random.choice([999.0, 1299.0]),
            "category_id": cat_id,
            "is_active": True,
            "tags": ["batch2"],
            "variants": [
                {"size": "S", "color": "White", "stock_qty": 100, "sku": f"SIM2-{i}-S-WHT"}
            ]
        }
        r = requests.post(f"{BASE_URL}/admin/products", json=payload, headers=admin_headers)
        if r.status_code == 201:
            created_product_ids.append(r.json()["id"])
    print(f"✅ Added 20 more products. Total active testing products: {len(created_product_ids)}")

    # 6. Customer Flow
    print_step("Customer Flow: Registering/Logging in as test user...")
    reg_r = requests.post(f"{BASE_URL}/auth/register", json={"email": "testuser@example.com", "password": "password123", "first_name": "Test", "last_name": "User"})
    if reg_r.status_code not in (201, 400):
        print("❌ Register failed:", reg_r.text)
        return
    r = requests.post(f"{BASE_URL}/auth/login", json={"email": "testuser@example.com", "password": "password123"})
    if r.status_code != 200:
        print("❌ Login failed:", r.text)
        return
    user_token = r.json()["access_token"]
    user_headers = {"Authorization": f"Bearer {user_token}"}
    print("✅ Customer authenticated.")

    # Fetch products to buy
    print_step("Customer browsing categories...")
    r = requests.get(f"{BASE_URL}/products?per_page=10")
    browse_products = r.json()["items"]
    print(f"✅ Browsed {len(browse_products)} products on frontend.")

    product_to_buy = browse_products[0]
    r = requests.get(f"{BASE_URL}/products/{product_to_buy['slug']}")
    product_details = r.json()
    variant_to_buy = product_details["variants"][0]

    # Wishlist
    print_step("Adding to Wishlist...")
    requests.post(f"{BASE_URL}/wishlist/{product_to_buy['id']}", headers=user_headers)
    
    print_step("Removing from Wishlist...")
    requests.delete(f"{BASE_URL}/wishlist/{product_to_buy['id']}", headers=user_headers)
    print("✅ Wishlist flow tested.")

    # Checkout
    print_step("Customer Checkout Flow...")
    order_payload = {
        "items": [
            {
                "variant_id": variant_to_buy["id"],
                "quantity": 2
            }
        ],
        "shipping_address": {
            "full_name": "Test User",
            "line1": "123 Test St",
            "city": "Mumbai",
            "state": "MH",
            "pin": "400001",
            "phone": "9999999999"
        }
    }
    r = requests.post(f"{BASE_URL}/orders", json=order_payload, headers=user_headers)
    if r.status_code != 201:
        print("❌ Checkout failed!", r.text)
        return
    order_data = r.json()
    order_id = order_data["id"]
    print(f"✅ Order {order_id} placed successfully.")

    # Payment Confirmation
    print_step("Confirming Payment...")
    payment_payload = {
        "order_id": order_id,
        "payment_method": "credit_card",
        "card_number": "4242 4242 4242 4242",
        "expiry": "12/25",
        "cvv": "123"
    }
    r = requests.post(f"{BASE_URL}/payments/confirm", json=payment_payload, headers=user_headers)
    print(f"✅ Payment Confirmed. Status: {r.json()['status']}")

    # Order tracking
    print_step("Customer tracking order...")
    r = requests.get(f"{BASE_URL}/orders/me", headers=user_headers)
    my_orders = r.json()
    print(f"✅ Customer has {len(my_orders)} orders in history.")
    
    print("\n🎉 SIMULATION TEST COMPLETE! 🎉")
    print("All endpoints (Admin CRUD & Customer Flow) validated successfully.")

if __name__ == "__main__":
    test_simulation()
